### ISSUE TITLE
请问有中文的prompt吗

### ISSUE THREAD

**Issue by renmengjie7** [18907305772/KCA#2]
prompt_bank下有三个英文的prompt, 请问有对应的效果不错的中文prompt吗?

**Comment by fanqiwan** [comment]
你好，我没有尝试过在中文上进行实验，你可以尝试用 GPT-4 将对应 prompt 翻译成中文。

**Comment by 18907305772** [comment]
你好，我没有尝试过在中文上进行实验，你可以尝试用 GPT-4 将对应 prompt 翻译成中文。

**Comment by renmengjie7** [comment]
> 你好，我没有尝试过在中文上进行实验，你可以尝试用 GPT-4 将对应 prompt 翻译成中文。

好的! 感谢
